service: hotline-apply

provider:
    name: aws
    runtime: nodejs8.10
    region: us-east-1
    stage: ${opt:stage, 'prod'}
    memorySize: 128
    environment:
        NODE_ENV: ${self:provider.stage, 'prod'}
        SESSION_TABLE: hotline-apply-session
        VAULT_ADDR: ${opt:vault-address}
        VAULT_ROLE_ID: ${opt:vault-role-id}
        VAULT_SECRET_ID: ${opt:vault-secret-id}

plugins:
    - serverless-domain-manager
    - serverless-offline

custom:
    customDomain:
        domainName: apply.hotline.gg
        stage: ${self:provider.stage}
        certificateName: 'hotline.gg'
        createRoute53Record: false

functions:
    app:
        handler: index.handler
        events:
            -   http: ANY /
            -   http: 'ANY {proxy+}'

resources:
    Resources:
        DynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: hotline-apply-session
                AttributeDefinitions:
                    -   AttributeName: id
                        AttributeType: S
                KeySchema:
                    -   AttributeName: id
                        KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 5
                    WriteCapacityUnits: 5
        DynamoDBIamPolicy:
            Type: AWS::IAM::Policy
            DependsOn: DynamoDbTable
            Properties:
                Roles: [{Ref: IamRoleLambdaExecution}]
                PolicyName: lambda-dynamodb
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        -   Effect: Allow
                            Action:
                                - dynamodb:DescribeTable
                                - dynamodb:CreateTable
                                - dynamodb:GetItem
                                - dynamodb:PutItem
                                - dynamodb:DeleteItem
                                - dynamodb:UpdateItem
                            Resource: arn:aws:dynamodb:us-east-1:452389113878:table/hotline-apply-session
        ApiGatewayPolicy:
            Type: "AWS::IAM::Policy"
            Properties:
                Roles: [{Ref: IamRoleLambdaExecution}]
                PolicyName: api-gateway
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                        -   Effect: Allow
                            Action:
                                - apigateway:POST
                            Resource: !Sub arn:aws:apigateway:us-east-1::/domainnames
                        -   Effect: Allow
                            Action:
                                - apigateway:GET
                                - apigateway:DELETE
                            Resource: !Sub arn:aws:apigateway:us-east-1::/domainnames/*
                        -   Effect: Allow
                            Action:
                                - apigateway:POST
                            Resource: !Sub arn:aws:apigateway:us-east-1::/domainnames/*/basepathmappings
                        -   Effect: Allow
                            Action:
                                - cloudfront:UpdateDistribution
                            Resource: '*'
                        -   Effect: Allow
                            Action:
                                - route53:ListHostedZones
                            Resource: '*'
                        -   Effect: Allow
                            Action:
                                - acm:ListCertificates
                            Resource: '*'
